# Base configs
baseurl: "https://allashumko.github.io"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
# google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Alla Shumko"
subtitle: "Nature and animal photographer"
author: "Alla Shumko"
header:
 title: "Photography"
 subtitle: "by Alla Shumko"
footer:
 name: "Hey there, my name is Alla"
 bio: "I am a nature and animal photographer based out of Big Bear, California."
 #github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/ramswaroop"
  twitter: "https://www.twitter.com/ram__patra"
  instagram: "https://www.instagram.com/ram_patra"
  dribbble: "https://dribbble.com/rampatra"
  linkedin: "https://in.linkedin.com/in/ram-patra"
  github: "https://www.github.com/allashumko"
